AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Lambda function for Amazon Connect PSTN Transfer"

Parameters:
  LambdaImplementation:
    Type: String
    Description: Lambda implementation type
    AllowedValues:
      - go
      - typescript
    Default: go

  OAuthClientId:
    Type: String
    NoEcho: true
    Description: OAuth 2 Client ID for authentication
    MinLength: 1

  OAuthClientSecret:
    Type: String
    NoEcho: true
    Description: OAuth 2 Client Secret for authentication
    MinLength: 1

  VirtualAgentName:
    Type: String
    Description: "Resource name of the virtual agent. Format: customers/{customer}/profiles/{profile}/virtualAgents/{virtualAgentID}"
    MinLength: 1

  Region:
    Type: String
    Description: "AWS region (e.g. us-west-2-prod, chat-prod, voice-prod, us-east-1-prod, schwab-prod, ca-central-1-prod, ap-southeast-2-prod, eu-west-2-prod). Defaults to us-west-2-prod"
    Default: "us-west-2-prod"

  CodeS3Bucket:
    Type: String
    Description: S3 bucket name containing the Lambda deployment package
    MinLength: 1

  CodeS3Key:
    Type: String
    Description: S3 key (path) to the Lambda deployment package (zip file). Defaults based on implementation type if not provided.
    Default: ""

  FunctionName:
    Type: String
    Description: Name for the Lambda function
    Default: "aws-lambda-connect-pstn-transfer"

  RoleName:
    Type: String
    Description: Name for the IAM role
    Default: "aws-lambda-connect-pstn-transfer-role"

Conditions:
  IsGoImplementation: !Equals [!Ref LambdaImplementation, "go"]
  UseDefaultCodeS3Key: !Equals [!Ref CodeS3Key, ""]

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Name
          Value: !Sub "${RoleName}"

  ConnectPSTNTransferFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: !If
        - IsGoImplementation
        - provided.al2023
        - nodejs24.x
      Handler: !If
        - IsGoImplementation
        - bootstrap
        - dist/handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !If
          - UseDefaultCodeS3Key
          - !If
            - IsGoImplementation
            - aws-lambda-connect-pstn-transfer-go.zip
            - aws-lambda-connect-pstn-transfer-ts.zip
          - !Ref CodeS3Key
      Architectures:
        - arm64
      Environment:
        Variables:
          oauthClientId: !Ref OAuthClientId
          oauthClientSecret: !Ref OAuthClientSecret
          region: !Ref Region
          virtualAgentName: !Ref VirtualAgentName
      Tags:
        - Key: Name
          Value: !Sub "${FunctionName}"
        - Key: Implementation
          Value: !Ref LambdaImplementation

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt ConnectPSTNTransferFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionArn"

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref ConnectPSTNTransferFunction
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionName"

  IAMRoleArn:
    Description: ARN of the IAM role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-IAMRoleArn"
