AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Lambda function for Amazon Connect PSTN Transfer"

Parameters:
  LambdaImplementation:
    Type: String
    Description: Lambda implementation type
    AllowedValues:
      - go
      - typescript
      - python
    Default: go

  OAuthSecretArn:
    Type: String
    Description: ARN of the AWS Secrets Manager secret containing OAuth credentials (JSON with oauthClientId and oauthClientSecret fields). If provided, takes precedence over OAuthClientId/OAuthClientSecret.
    Default: ""

  OAuthClientId:
    Type: String
    NoEcho: true
    Description: OAuth 2 Client ID for authentication (required if OAuthSecretArn is not provided)
    Default: ""

  OAuthClientSecret:
    Type: String
    NoEcho: true
    Description: OAuth 2 Client Secret for authentication (required if OAuthSecretArn is not provided)
    Default: ""

  VirtualAgentName:
    Type: String
    Description: "Resource name of the virtual agent. Format: customers/{customer}/profiles/{profile}/virtualAgents/{virtualAgentID}"
    MinLength: 1

  Region:
    Type: String
    Description: "AWS region (e.g. us-west-2-prod, chat-prod, voice-prod, us-east-1-prod, ca-central-1-prod, ap-southeast-2-prod, eu-west-2-prod). Required if ApiDomain is not provided. Defaults to us-west-2-prod"
    Default: "us-west-2-prod"

  ApiDomain:
    Type: String
    Description: "API domain without protocol prefix (e.g., api-customer-profile.cresta.com). Optional. If provided, the region will be extracted from the domain."
    Default: ""

  AuthDomain:
    Type: String
    Description: "OAuth authentication domain without protocol prefix (e.g., auth.us-west-2-prod.cresta.ai). Optional. Must be provided together with ApiDomain."
    Default: ""

  CodeS3Bucket:
    Type: String
    Description: S3 bucket name containing the Lambda deployment package
    MinLength: 1

  CodeS3Key:
    Type: String
    Description: S3 key (path) to the Lambda deployment package (zip file). Defaults based on implementation type if not provided.
    Default: ""

  FunctionName:
    Type: String
    Description: Name for the Lambda function
    Default: "aws-lambda-connect-pstn-transfer"

  RoleName:
    Type: String
    Description: Name for the IAM role
    Default: "aws-lambda-connect-pstn-transfer-role"

Conditions:
  IsGoImplementation: !Equals [!Ref LambdaImplementation, "go"]
  IsTypeScriptImplementation: !Equals [!Ref LambdaImplementation, "typescript"]
  IsPythonImplementation: !Equals [!Ref LambdaImplementation, "python"]
  UseDefaultCodeS3Key: !Equals [!Ref CodeS3Key, ""]
  UseSecretsManager: !Not [!Equals [!Ref OAuthSecretArn, ""]]

Rules:
  CredentialsRequired:
    Assertions:
      - Assert: !Or
          - !Not [!Equals [!Ref OAuthSecretArn, ""]]
          - !And
            - !Not [!Equals [!Ref OAuthClientId, ""]]
            - !Not [!Equals [!Ref OAuthClientSecret, ""]]
        AssertDescription: "Either OAuthSecretArn or both OAuthClientId and OAuthClientSecret must be provided"
      - Assert: !Or
          - !Equals [!Ref ApiDomain, ""]
          - !Not [!Equals [!Ref AuthDomain, ""]]
          - !And
            - !Equals [!Ref OAuthSecretArn, ""]
            - !Or
              - !Equals [!Ref OAuthClientId, ""]
              - !Equals [!Ref OAuthClientSecret, ""]
        AssertDescription: "When ApiDomain is provided with OAuth credentials (OAuthSecretArn or OAuthClientId/OAuthClientSecret), AuthDomain must also be provided"

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - !If
          - UseSecretsManager
          - PolicyName: SecretsManagerAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - secretsmanager:GetSecretValue
                  Resource: !Ref OAuthSecretArn
          - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub "${RoleName}"

  ConnectPSTNTransferFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: !If
        - IsGoImplementation
        - provided.al2023
        - !If
          - IsPythonImplementation
          - python3.14
          - nodejs24.x
      Handler: !If
        - IsGoImplementation
        - bootstrap
        - !If
          - IsPythonImplementation
          - src.handler.handler
          - handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !If
          - UseDefaultCodeS3Key
          - !If
            - IsGoImplementation
            - aws-lambda-connect-pstn-transfer-go.zip
            - !If
              - IsPythonImplementation
              - aws-lambda-connect-pstn-transfer-py.zip
              - aws-lambda-connect-pstn-transfer-ts.zip
          - !Ref CodeS3Key
      Architectures:

        - !If [IsPythonImplementation, x86_64, arm64]
      Environment:
        Variables:
          oauthSecretArn: !Ref OAuthSecretArn
          oauthClientId: !Ref OAuthClientId
          oauthClientSecret: !Ref OAuthClientSecret
          region: !Ref Region
          apiDomain: !Ref ApiDomain
          authDomain: !Ref AuthDomain
          virtualAgentName: !Ref VirtualAgentName
      Tags:
        - Key: Name
          Value: !Sub "${FunctionName}"
        - Key: Implementation
          Value: !Ref LambdaImplementation

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt ConnectPSTNTransferFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionArn"

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref ConnectPSTNTransferFunction
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionName"

  IAMRoleArn:
    Description: ARN of the IAM role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-IAMRoleArn"
